services:
  app:
    build: ./app
    container_name: back
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./task-manager-frontend
    container_name: front
    ports:
      - "80:80"
    depends_on:
      - app

  